services:
  zola:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b01_zola
    ports:
      - "8180:8180"
    restart: unless-stopped

networks:
  caddy:
    external: true

