services:
  zola:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b01_zola
    networks:
      - caddy
    labels:
      caddy: www.betweenzeroand.one
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped

networks:
  caddy:
    external: true

